services:
  auth-service:
    build: ./Auth-Service
    container_name: auth-service
    ports:
      - "3002:3002"
    env_file:
      - ./Auth-Service/.env
    networks:
      - nodejs-monitoring
    restart: unless-stopped

  item-service:
    build: ./Item-Service
    container_name: item-service
    ports:
      - "3001:3001"
    env_file:
      - ./Item-Service/.env
    networks:
      - nodejs-monitoring
    restart: unless-stopped

  load-test:
    image: python:3.11-slim
    container_name: load-test
    depends_on:
      - item-service
      - auth-service
    volumes:
      - ./scripts:/scripts
    environment:
      - TARGET_URL=http://item-service:3001
      - MAX_USERS=30
      - DURATION=600
      - CYCLE=120
    command: >
      sh -c "pip install requests && python /scripts/load_test.py"
    networks:
      - nodejs-monitoring
    restart: no

networks:
  nodejs-monitoring:
    driver: bridge
